api_key: 8LyQJtMQKeXTo5Gn1ljj9afJq
api_secret: rZyvEOMWVIxhWk8hX0GMy2iHiuaIMhMSCQ18TvRX0fdhArg2Xo
oauth_token: 1157156125-4orIOHxHD3ZiPKQTEmgo70aRPsx09yskPUj5OII
oauth_secret: 33dYS6pRGecl0Un1jTKpoHpWWjQl7GaHLTySEJhslYe7B


# api_key: 0f17DpkRfBKBogkPeuKv5AP2E
# api_secret: OjXN15csDDe39oenhuBEiVNHZ6ygHR44VkGkt9UDlcPeXe5I65
# oauth_token: 2532931414-cjdo3Jjt6PmWj2vzp5LQHcEpswG6opox8Zfi0d2
# oauth_secret: uHqihbCRrvkwqeL5ctN3TPgPsyJT7Doy1ghx9jFrgXMhK

# api_key: widuj5xJZ7VlIGc4esW7RQ
# api_secret: V9OjB8dhb1vv6LqmWfmaZXrIo52lg4mKAatfD890Ng
# oauth_token: 1157156125-ifIlgn4l6SDEOSwv4Eet7fESFog52CsupWjxPoI
# oauth_secret: PDCCXOhBWa4aAmHY9Tn2N7sYjVj544XIFahebJerkA


mandrill_username: chalcchuck@gmail.com
mandrill_password: M7Jq76c4ZNwr__ww5Hj3kA

development:
 host: "localhost:3000"
production:
 host: "testserver.com"
sandbox:
 host: "testserver.com"
test:
 host: "localhost:3000"