source "https://rubygems.org"

# Declare your gem's dependencies in twitter_parser.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
gem 'debugger'
gem 'sass-rails', '~> 4.0.3'
gem 'bootstrap-sass'
gem 'sass', '3.2.13'
gem 'will_paginate'
gem 'sidekiq'
gem 'figaro'
gem 'coffee-rails'
gem 'jquery-rails'